---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: toolbox
  namespace: default
spec:
  selector:
    matchLabels:
      app: toolbox 
  serviceName: "debug"
  replicas: 1
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: toolbox
        image: cmarasescu/toolbox:1.0
